# Config for https://github.com/toolmantim/release-drafter
name-template: 'Akka Paradox theme $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🚀 Enhancements'
    label: 'enhancement'

change-template: '- $TITLE [#$NUMBER](https://github.com/akka/akka-paradox/issues/$NUMBER) by [@$AUTHOR](https://github.com/$AUTHOR)'

template: |
  ## Changes

  $CHANGES
