language: scala

before_install:
  # using jabba for custom jdk management
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | bash && . ~/.jabba/jabba.sh
  - jabba install $TRAVIS_JDK
install: jabba use "$TRAVIS_JDK" && java -Xmx32m -version

script:
  - sbt test

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.jabba/jdk

deploy:
  provider: script
  script:
    - sbt publish
  on:
    tags: true
    repo: akka/akka-paradox

env:
  global:
    - TRAVIS_JDK=adopt@~1.8.0-222
