name: Publish

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  sbt:
    name: sbt publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8

      - name: Publish
        run: |-
          sbt ci-release
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
